name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "EduardoDosSantosFerreira"
          git config --global user.email "eduardosferreira69@gmail.com"

      - name: Verificar se existe a branch update
        id: update
        run: |
          # Verificar se existe a branch 'update'
          git fetch --all
          if git show-ref --verify --quiet refs/heads/update; then
            echo "A branch 'update' já existe."
          else
            echo "A branch 'update' não existe. Criando..."
            git checkout -b update
            git push origin update
          fi

      - name: Commit e Push
        run: |
          # Atualizar o repositório
          git pull origin main

          # Adicionar mudanças e realizar commit
          git add .

          # Fazer commit com a mensagem personalizada
          git commit -m "Atualização automática: update - $(date +'%Y-%m-%d %H:%M:%S')" || exit 0

          # Enviar alterações para o repositório
          git push origin update
