name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que todas as referências do histórico sejam baixadas

      - name: Configurar Git
        run: |
          git config --global user.name "EduardoDosSantosFerreira"
          git config --global user.email "eduardosferreira69@gmail.com"

      - name: Configurar URL Remota para usar o Token
        run: |
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/EduardoDosSantosFerreira/Portfolio.git

      - name: Atualizar repositório local
        run: |
          git pull origin main --rebase  # Usa rebase para evitar conflitos desnecessários

      - name: Commit e Push
        run: |
          git add .
          COMMIT_MESSAGE="auto_update: ($(date +'%Y-%m-%d')) - ($(date +'%H:%M:%S'))"
          git commit --allow-empty -m "$COMMIT_MESSAGE"
          git push origin main
